# Generated by Django 5.1.4 on 2025-03-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='end_lat',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='marker',
            name='end_lon',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='marker',
            name='start_lat',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='marker',
            name='start_lon',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
