# Generated by Django 5.1.4 on 2025-03-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_marker_end_lat_alter_marker_end_lon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='marker',
            name='end_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marker',
            name='end_lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marker',
            name='start_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marker',
            name='start_lon',
            field=models.FloatField(),
        ),
    ]
