# Generated by Django 5.1.4 on 2025-03-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_message_is_read_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
    ]
