# Generated by Django 5.1.4 on 2025-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_marker_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_notification',
            field=models.BooleanField(default=False),
        ),
    ]
