# Generated by Django 5.1.7 on 2025-03-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_message_is_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='users',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
