# Generated by Django 5.1.7 on 2025-03-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_marker_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='users',
            field=models.JSONField(blank=True),
        ),
    ]
