# Generated by Django 5.1.4 on 2025-03-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_marker_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='users',
            field=models.JSONField(default=dict),
        ),
    ]
