# Generated by Django 5.1.4 on 2025-03-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_marker_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trips',
            field=models.JSONField(default=dict),
        ),
    ]
