# Generated by Django 5.1.4 on 2025-03-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='profile_photos/'),
            preserve_default=False,
        ),
    ]
