# Generated by Django 5.1.4 on 2025-03-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_photos/default_profile.jpg', upload_to='static/profile_photos/'),
        ),
    ]
