# Generated by Django 5.1.4 on 2025-03-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='landmark_photo',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/images/'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='marker',
            name='transport_type',
            field=models.CharField(choices=[('personal', 'Личный транспорт'), ('carsharing', 'Каршеринг'), ('taxi', 'Такси'), ('searching', 'Ищу транспорт'), ('other', 'Другое')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/default_profile.jpg', upload_to='main/static/images/'),
        ),
    ]
